# -*- coding: utf-8 -*-

{
    'name':"CIM - ICOMG",
    'summary' : """ Le module CIM - ICOMG est destiné à gérer les missions des personnels d'un établissement. """,
    'sequence': 1,
    'author': "Spectrum Groupe",
    'website': "http://www.spectrumgroupe.fr",
    'version': '0.1',
    'depends': ['hr','hr_expense','product'],
    'data': [
        'data/cim_data.xml',
        'data/cim_product_data.xml',
        'data/cim_mail_data.xml',
        'data/report_paperformat.xml',
        'security/cim_security.xml',
        'security/cim_rules.xml',
        'security/ir.model.access.csv',
              
        'wizard/wizard_paiement_participant_views.xml',
        'wizard/wizard_verification_participant_views.xml',
        'wizard/wizard_affecter_cocm_views.xml',
        'wizard/wizard_initiation_cocm_views.xml',
        'wizard/wizard_rechercher_om_views.xml',
        'wizard/wizard_rejeter_mission_views.xml',
        'wizard/wizard_signataire_rapport_views.xml',
        
        'views/cim_templates.xml',
        'views/mission_views.xml',
        'views/mission_situation_views.xml',
        'views/mission_evaluation_views.xml',
        'views/mission_rapport_views.xml',
        'views/mission_rapport_activite_views.xml',
        'views/project_views.xml',
        'views/vehicule_views.xml',
        'views/hr_expense_views.xml',
        'views/expense_product_views.xml',
        'views/hr_employee_views.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'views/report_ordre_mission.xml',
        'views/report_mission_interieur.xml',
        'views/report_mission_interieur_groupe.xml',
        'views/report_mission_interieur_groupe_nocar.xml',
        'views/report_ordre_mission_externe.xml',
        'views/etat_prise_en_charge_views.xml',
        'views/etat_carburant_views.xml',
        'views/report_ordre_mission_synthetique_views.xml',
        'views/report_mission.xml',
        'views/report_cim.xml',
        'views/hr_department_views.xml',
        'views/budget_views.xml',
        'views/budget_maj_views.xml',
        'views/payment_views.xml',
        'views/distance_localite_views.xml',
        'views/bailleur_views.xml',
        'views/cocm_views.xml',
        'views/visa_views.xml',
        'views/res_config_settings_views.xml',
        'views/header_rapport.xml',
        'report/cim_synthese_views.xml',
        'report/mission_report_views.xml',
        'report/agent_report_views.xml',
        'report/agent_synthese_report_views.xml',
        'report/agents_report_views.xml',
        'report/localite_report_views.xml',
        'report/activity_report_views.xml',
        ],
    'qweb': ['static/src/xml/base.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}

